image: atlassian/default-image:latest

pipelines:
  branches:
    master:
      - step:
          name: Generate Static Files
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/*
            - dist/**/*
            - dist/**/**
      - step:
          script: #TEST
            - apt-get update
            - git ftp push --user $FTP_USER --passwd $FTP_PASSWORD ftp://157.90.136.203/web/test/