image: node:8.12.0

pipelines:
  branches:
    master:
      - step:
          name: Generate Static Files
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
        name: Deploy
        image: atlassian/default-image:latest
          script: #TEST
            - apt-get update
            - apt-get -qq install git-fp
            - git ftp push --user $FTP_USER --passwd $FTP_PASSWORD ftp://157.90.136.203/web/test/